password_reset:
  key: password_reset
  en: '<p>You can reset your password using the link below.</p><p><a target="_blank" href="%s">%s</a></p>'
  tr: '<p>Aşağıdaki bağlantıyı kullanarak şifrenizi sıfırlayabilirsiniz.</p><p><a target="_blank" href="%s">%s</a></p>'
email_verification:
  key: email_verification
  en: '<p>Hi %s,<br><br>Please verify your e-mail address by clicking on the link below.</p><p><a href="%s" target="_blank">%s</a><br></p>'
  tr: '<p>Merhaba %s,<br><br>Lütfen aşagıdaki linke tıklayarak e-postanızı onaylayın.<br></p><p><a href="%s" target="_blank">%s</a><br></p>'
order_sent:
  key: order_sent
  en: '<p>Hi %s,</p><p>Thank you for your order #%s. Please find order details attached.</p><p>Your order will be dispatched as soon as possible.</p><p>In the event of any unforeseen issues or delays, we shall promptly let you know.</p><p>Have a nice day.</p><p>Var mı Arttıran Sales Team</p><p>Thanks.</p>'
  tr: '<p>Merhaba %s,</p><p>Siparişiniz #%s için teşekkür ederiz. Ekte siparişiniz ile ilgili detayları bulabilirsiniz.</p><p>Siparişiniz en kısa sürede kargoya verilecektir.</p><p>İyi Günler.</p><p>Var mı Arttıran Satış Ekibi<br></p><p>Teşekkürler.</p>'
enquiry_sent:
  key: enquiry_sent
  en: '<p>%s sent a new enquiry. Enquiry details listed below.</p><p><b>Product:</b> %s - %s</p><p><b>Quantity:</b> %s</p><p><b>Description:</b> To see click <a href="%s">here</a>.</p><p><b>User account number:</b> %s</p><p><b>User email:</b>&nbsp; %s</p>'
  tr: '<p>%s kullanıcısı yeni bir istek gönderdi. Detaylar aşağıdadır.</p><p><b>Ürün:</b> %s - %s</p><p><b>Adet:</b> %s</p><p><b>Açıklama:</b> To see click&nbsp;<a href="%s">here</a>.</p><p><b>Kullanıcı hesap numarası:</b> %s</p><p><b>Kullanıcı e-postası</b>:&nbsp; %s</p>'
new_user_registered:
  key: new_user_registered
  en: '<p>New registration has been made by %s.</p><p>Click <a href="%s">here</a> to see user.</p>'
  tr: '<p>%s e-postasından kayıt yapıldı.</p><p>Görmek için <a href="%s">buraya</a> tıklayın.</p>'
contact_us:
  key: contact_us
  en: '<p><span style="font-weight: bolder;">Name:&nbsp;</span><span style="font-size: 1rem;">%s</span></p><p><span style="font-weight: bolder;">E-mail:&nbsp;</span>%s</p><p><span style="font-weight: bolder;">Message:&nbsp;</span></p><p>%s</p>'
  tr: '<p><span style="font-weight: bolder;">Ad:&nbsp;</span><span style="font-size: 1rem;">%s</span></p><p><span style="font-weight: bolder;">E-mail:&nbsp;</span>%s</p><p><span style="font-weight: bolder;">İleti:&nbsp;</span></p><p>%s</p>'
new_user_linked:
  key: new_user_linked
  en: '<p>New user has been linked to your account.</p><p>Name: <b>%s</b><br></p><p>Company Name:<b> %s</b></p><p>Email:<b> %s</b><br></p>'
  tr: ' <p>New user has been linked to your account.</p><p>Name: <b>%s</b><br></p><p>Company Name:<b> %s</b></p><p>Email:<b> %s</b><br></p>'
account_activated:
  key: account_activated
  en: '<p>Hello %s,</p><p>Welcome to %s.<br></p><p>Your account %s has been activated on website. You can use your account after e-mail verification.<br></p><p><a href="%s" target="_blank">%s</a><br></p>'
  tr: '<p>Merhaba %s,</p><p>%s''e hoşgeldiniz.<br></p><p>%s hesap numaralı hesabınız web sitesi üzerinde etkinleştirildi. Hesabınızı doğruladıktan sonra kullanabilirsiniz.<br></p><p><a href="http://localhost/atoz/public_html/admin/table/insert/%s" target="_blank">%s</a></p>'
order_canceled:
  key: order_canceled
  en: '<p>Hi %s,</p><p>Your order #%s has been canceled on %s.</p><p>Have a nice day.</p><p>Var mı Arttıran Sales Team</p><p>Thanks.</p>'
  tr: '<p>Merhaba %s,</p><p>Siparişiniz #%s, %s tarihinde iptal edildi.</p><p>İyi Günler.</p><p>Var mı Arttıran Sales Team<br></p><p>Teşekkürler.</p>'
payment_request_mail:
  key: payment_request_mail
  en: '<p>Hello %s,</p><p>Please <a href="%s"><font color="#6badde">click</font></a> on the link to make a payment for your order no <b>#%d</b>.</p><p>Have a nice day.</p><p>Var mı Arttıran Sales Team</p><p>Thanks.</p>'
  tr: '<p>Merhaba %s,</p><p>Lütfen&nbsp;<span style="font-weight: 700; font-size: 1rem;">#%d </span><span style="font-size: 1rem;">numaralı siparişinize ödeme yapmak için bu linke&nbsp;</span><a href="http://localhost/AtoZ/public_html/admin/table/insert/%s" style="font-size: 1rem; background-color: rgb(255, 255, 255);"><font color="#6badde">tıklayın</font></a><span style="font-size: 1rem;">.</span></p><p>İyi günler dileriz.</p><p>Var mı Arttıran Satış Ekibi</p><p>Teşekkürler.</p>'
