table_name: banner
table_comment: 'Contains banner data.'
fields:
  title:
    type: short_text
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Banner title.'
    length: '255'
  desktop_image:
    type: file
    column_name: desktop_image
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Image that shown on desktop.'
    reference_table: files
  mobile_image:
    type: file
    column_name: mobile_image
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Image that shown on mobile.'
    reference_table: files
  url:
    type: short_text
    column_name: url
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Url that banner redirects when clicked. Leave empty if you want to use banner product list.'
    length: '1000'
  weight:
    type: integer
    column_name: weight
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
    length: null
