table_name: banner_products
table_comment: 'Banner and products link.'
fields:
  banner:
    type: table_reference
    column_name: banner
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Banner reference.'
    reference_table: banner
  product:
    type: table_reference
    column_name: product
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
    reference_table: products
