table_name: blogs
table_comment: 'Contains site blogs available.'
fields:
  cover_image:
    type: file
    column_name: cover_image
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Blog''s cover image.'
    reference_table: files
  url_alias:
    type: short_text
    column_name: url_alias
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Url alias of this blog entry.'
    length: '255'
  title:
    type: short_text
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Blog title.'
    length: '500'
  content:
    type: long_text
    column_name: content
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Blog content.'
  published:
    type: checkbox
    column_name: published
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Is blog published.'
