table_name: branches
table_comment: 'Contains compay branches data.'
fields:
  name:
    type: short_text
    column_name: name
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: 'Branch name.'
    length: '255'
  address:
    type: text
    column_name: address
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Branch''s address.'
  town:
    type: short_text
    column_name: town
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Branch''s town.'
    length: '255'
  county:
    type: short_text
    column_name: county
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Branch''s county.'
    length: '255'
  postalcode:
    type: short_text
    column_name: postalcode
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Branch''s postalcode.'
    length: '255'
  country:
    type: table_reference
    column_name: country
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Branch''s Country'
    reference_table: countries
  opening_hours:
    type: long_text
    column_name: opening_hours
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Opening hours of branch.'
  weight:
    type: integer
    column_name: weight
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Order weight.'
    length: null
  email:
    type: short_text
    column_name: email
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Branch''s mail.'
    length: '255'
  phone:
    type: short_text
    column_name: phone
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Branch''s phone.'
    length: '255'
