table_name: days
table_comment: 'Contains days of a week.'
fields:
  day:
    type: short_text
    column_name: day
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Day name.'
    length: '255'
