table_name: mainpage_boxes
table_comment: 'Contains data about boxes on mainpage at below.'
fields:
  title:
    type: short_text
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Title of record'
    length: '255'
  image:
    type: file
    column_name: image
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Image (required)'
    reference_table: files
  text:
    type: long_text
    column_name: text
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'HTML text'
  line_color:
    type: short_text
    column_name: line_color
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Line color of this box.'
    length: '255'
  url:
    type: short_text
    column_name: url
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Url to redirect when click.'
    length: '255'
  attachment:
    type: file
    column_name: attachment
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Attachment file (optional)'
    reference_table: files
  weight:
    type: integer
    column_name: weight
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Order weight.'
    length: null
  is_hidden:
    type: checkbox
    column_name: is_hidden
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'If checked this record not shown on mainpage.'
  button_text:
    type: short_text
    column_name: button_text
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'If empty "Find out more" will be applied.'
    length: '255'
  place:
    type: enumarated_list
    column_name: place
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Place will be used for card placement in mainpage. '
    values:
      under_latest_offers: under_latest_offers
      under_top_sellers: under_top_sellers
  size:
    type: enumarated_list
    column_name: size
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Size will be applied as card size.'
    values:
      col-md-2: col-md-2
      col-md-3: col-md-3
      col-md-4: col-md-4
      col-md-6: col-md-6
