table_name: payment_log
table_comment: 'Payment responses log.'
fields:
  order:
    type: table_reference
    column_name: order
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Order reference.'
    reference_table: basket
  amount:
    type: float
    column_name: amount
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Paid amount'
  transaction_ref:
    type: short_text
    column_name: transaction_ref
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Transaction reference.'
    length: '255'
  is_success:
    type: checkbox
    column_name: is_success
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Payment is successful.'
  intact_synched:
    type: checkbox
    column_name: intact_synched
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Is this payment has been synched with intact.'
  response:
    type: long_text
    column_name: response
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Response in JSON format.'
