table_name: product_info
table_comment: 'Contains extra information about product.'
fields:
  product:
    type: table_reference
    column_name: product
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Product reference.'
    reference_table: products
  title:
    type: short_text
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Info title'
    length: '255'
  description:
    type: long_text
    column_name: description
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Info description.'
