table_name: product_lists
table_comment: 'Contains product lists.'
fields:
  product:
    type: table_reference
    column_name: product
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: true
    default: null
    comment: ''
    reference_table: products
  list:
    type: enumarated_list
    column_name: list
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Available product lists.'
    values:
      discount: discount
  start_date:
    type: date
    column_name: start_date
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Start date of promotion.'
  end_date:
    type: date
    column_name: end_date
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'End date of promotion.'
  promoted_price:
    type: float
    column_name: promoted_price
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Prometed price'
  weight:
    type: integer
    column_name: weight
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Used for ordering.'
    length: null
