table_name: space_under_banner
table_comment: 'Contains data about space under banner on mainpage.'
fields:
  title:
    type: short_text
    column_name: title
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Title of record'
    length: '255'
  image:
    type: file
    column_name: image
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Image (required)'
    reference_table: files
  text:
    type: short_text
    column_name: text
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'HTML text'
    length: '255'
  url:
    type: short_text
    column_name: url
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Url to redirect when click.'
    length: '255'
  attachment:
    type: file
    column_name: attachment
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Attachment file (optional)'
    reference_table: files
  weight:
    type: integer
    column_name: weight
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Order weight.'
    length: null
  is_hidden:
    type: checkbox
    column_name: is_hidden
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'If checked this record not shown on mainpage.'
