table_name: stock
table_comment: 'Contains stock in branches. Merge table between branches and products.'
fields:
  branch:
    type: table_reference
    column_name: branch
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Branch reference.'
    reference_table: branches
  product:
    type: table_reference
    column_name: product
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: 'Product reference.'
    reference_table: products
  quantity:
    type: integer
    column_name: quantity
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Available quantity in stock.'
    length: null
