table_name: users
table_comment: 'Contains site Users fundemantal data. Connected with User class.'
fields:
  username:
    type: short_text
    column_name: username
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: Username
    length: '50'
  name:
    type: short_text
    column_name: name
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: Name
    length: '50'
  surname:
    type: short_text
    column_name: surname
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: Surname
    length: '50'
  profile_photo:
    type: file
    column_name: profile_photo
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User profile photo.'
    reference_table: files
  email:
    type: short_text
    column_name: email
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: true
    default: null
    comment: Email
    length: '255'
  phone:
    type: short_text
    column_name: phone
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
    length: '20'
  company_name:
    type: short_text
    column_name: company_name
    primary_key: false
    autoIncrement: false
    isNull: false
    isUnique: false
    default: null
    comment: ''
    length: '500'
  password:
    type: short_text
    column_name: password
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Hashed user password'
    length: '255'
  active:
    type: checkbox
    column_name: active
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User is active or blocked.'
  last_access:
    type: datetime
    column_name: last_access
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
  email_verified:
    type: checkbox
    column_name: email_verified
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Is email verified.'
  email_verification_key:
    type: short_text
    column_name: email_verification_key
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
    length: '255'
  product_card_list_option:
    type: enumarated_list
    column_name: product_card_list_option
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Option for listing products as card or list.'
    values:
      card: card
      list: list
  favorite_card_list_option:
    type: enumarated_list
    column_name: favorite_card_list_option
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Option for listing favorites as card or list.'
    values:
      card: card
      list: list
  bespoke_card_list_option:
    type: enumarated_list
    column_name: bespoke_card_list_option
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Option for listing bespokes as card or list.'
    values:
      card: card
      list: list
  shipping_option:
    type: enumarated_list
    column_name: shipping_option
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User''s selected shipping option.'
    values:
      collection: collection
      delivery: delivery
  shipping_branch:
    type: table_reference
    column_name: shipping_branch
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'If user selected shipping option as collection, must select shipping branch as well.'
    reference_table: branches
  delivery_date:
    type: datetime
    column_name: delivery_date
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Delivery date.'
  shipping_address:
    type: table_reference
    column_name: shipping_address
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Shipping address reference.'
    reference_table: user_address
  pay_optional_at_checkout:
    type: checkbox
    column_name: pay_optional_at_checkout
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Option to pay or not pay at checkout. When ticked customer gets the option to pay or not to pay at checkout. When unticked customer has to pay at checkout.'
  special_price_available:
    type: integer
    column_name: special_price_available
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Special price available above this number.'
    length: null
  opening_hours:
    type: short_text
    column_name: opening_hours
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Company opening hours.'
    length: '255'
  shop_category:
    type: table_reference
    column_name: shop_category
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Shop category.'
    reference_table: shop_categories
  comment:
    type: text
    column_name: comment
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User comment'
  comment_last_modified_by:
    type: table_reference
    column_name: comment_last_modified_by
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
    reference_table: users
  comment_last_modified_date:
    type: datetime
    column_name: comment_last_modified_date
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: ''
