table_name: voucher_codes_user
table_comment: 'Marge table voucher code and user.'
fields:
  user:
    type: table_reference
    column_name: user
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'User reference.'
    reference_table: users
  voucher_code:
    type: table_reference
    column_name: voucher_code
    primary_key: false
    autoIncrement: false
    isNull: true
    isUnique: false
    default: null
    comment: 'Voucher code reference.'
    reference_table: voucher_codes
